Repository Julessh05-Studium/routing-algorithm, pull requests merged in 2025-02, with the labels that each got.

#2 Restructure objects and add comments
  .gitignore
  CMakeLists.txt
  algo.c
  algo.h
  io.c
  io.h
  main.c
  objects/dictionary.c
  objects/dictionary.h
  objects/route.c
  objects/route.h
Labels: documentation, feature, algorithm

#3 feat: add parser
  .clang-format
  CMakeLists.txt
  germany_map.csv
  main.c
  objects/dictionary.c
  objects/dictionary.h
  objects/route.h
  parser.c
  parser.h
Labels: feature, io, parsing

#4 Algorithm-2
  .idea/editor.xml
  CMakeLists.txt
  algo.c
  src/logic/algo.c
  src/logic/algo.h
  src/main.c
  src/objects/dictionary.c
  src/objects/dictionary.h
  src/objects/route.c
  src/objects/route.h
Labels: feature, algorithm

#24 Parser space check
  germany_map.csv
  src/parsing/parser.c
Labels: io, parsing

#27 Waypoints feature
  .gitignore
  .idea/editor.xml
  .idea/misc.xml
  .idea/runConfigurations/Dresden____Regensburg.xml
  .idea/runConfigurations/Dresden____Regensburg_Debug.xml
  .idea/runConfigurations/München____Karlsruhe.xml
  .idea/runConfigurations/München____Karlsruhe_Debug.xml
  .idea/runConfigurations/Nürnberg____Linz____München.xml
  .idea/runConfigurations/Stuttgart____Berlin.xml
  .idea/runConfigurations/Stuttgart____Bonn.xml
  .idea/runConfigurations/Stuttgart____Bonn_Debug.xml
  src/logic/algo.c
  src/logic/algo.h
  src/main.c
  src/objects/dictionary.c
  src/objects/dictionary.h
  src/parsing/parser.c
  src/parsing/parser.h
  src/reallife_application/fuel_consumption.c
  src/reallife_application/fuel_consumption.h
Labels: feature, optional, algorithm
